ITEM.name = "Dynamo"
ITEM.model = Model("models/jdoug/weapons/doug_dynamo.mdl")
ITEM.class = "d_dynamo"
ITEM.description = "A portable generator that can be used to power devices or provide light in dark areas. It has a hand crank that can be turned to generate electricity, making it useful in situations where traditional power sources are unavailable."
ITEM.category = "Tools"
ITEM.weaponCategory = "tool"
ITEM.width = 2
ITEM.height = 2
ITEM.noBusiness = false